### ISSUE TITLE
Using dplyr grammar when employing nest_in

### ISSUE THREAD

**Issue by fhui28** [emitanaka/nestr#3]
For example (I should say I love the options available for prefixing and leading zeros!), noting that is designed to produce different results to your original example

farmer <- c("John", "Jane", "Ann", "Thomas", "Helen")
nest_in(farmer, 
               "John" ~ 2,
    **Ann:Helen ~ 10,**
          . ~ 3,
        name = "chick",
        prefix = "chick-",
        leading0 = TRUE,
        min_ndigits = 4)

**Comment by emitanaka** [comment]
The grammar you are mentioning is from `tidyselect` (although you mostly see this via `dplyr`). I disagree with its use here because tidyselect syntax is for selection of _variables_ but your suggestion to use it for _levels_. Rows get shuffled around more often than columns so I reckon such a syntax make it more prone for the user to make a mistake. Having said that, there is kind of a way to do what you want by specifying the levels `3:5 ~ 10` or alternatively `farmer[3:5] ~ 10` should work too. I'm not too convinced that there is a strong case for above. 

Still appreciate your comments!

**Comment by fhui28** [comment]
That is fine. I am thinking of situations where you are dealing with factors involving lots of levels e.g, time points nested within hundreds to thousands of individuals, in which case there needs to be ways of doing assignment of number of measurements to a level at speed.
